language: java
jdk:
    - oraclejdk8
after_success:
- python <(curl -s https://raw.githubusercontent.com/lordOfSputnik/sputnik-test/master/sputnik-ci-common.py)
#- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

#env:
#  global:
#  - secure: Nfx/pLKL8XUW9QhQzWXwZRp1FRN7yRGIWtes4ZCR6qOZsPTOCM0dZxE3kqoYfkotuXwJ5dWDpgdRiMRsVdFwuuZTWxy1UhsyAPe9Rw2EA3unUUQaGty3+syjYd8GWaYwTBlaG8hQDNUagqRih/5BeCJ8ckmWhLu8Ln7qSFSnbVH2uT1uwq/yHFFjLQMHyCIxdyA/tQfZy4LoNGERqPfJcUoZxJKsNPpc0jg9//vwIEowTgp2yBHsvpfOz49D0dO+uplu96ippVnnQCZOQFLTDDSlOff9CMgsu2WYYzcUIsIaPeD0OfI2dWgCL4cG4hy5IIroiFACLWOqeYxvIW/50pwD77GOUOoPu4up0dqZk2cKmWB9NntT2bftuO4eHnABVqd0b+QOpSeOIiQxjV0H1ul8/f0JrFarK5QpW2Sf3N/hhZcjLWODqoVgkI9+aeBjSP7rsD6+2gOKmssLIKqU29PObjNBjr7bZqumh0fJYnNqR/ydO834z+9gALHn+dHAM2QX8j1h2qY9WeinnWGySnVt4Jx36TgeZOo1C+7uCdnHiJmA7jTxl1SncQH63X0BIx0kJ4c28HGkquJNSFqVWoDqH6k3sg2sHKzzk7GWIB7NlG8nY1jge7ZGw12PnTtCU+BqY+4MoVI8hffPULtfltcWLeSbSD2MOOcEZBxezys=