language: java
jdk:
    - oraclejdk8
after_success:
#- bash <(curl -s https://raw.githubusercontent.com/TouK/sputnik/saas/sputnik-ci.sh)
- python <(curl -s https://raw.githubusercontent.com/lordOfSputnik/sputnik-test/sputnikRulesViolated/sputnik-ci.py)